### ISSUE TITLE
DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by zaneschepke** [stfsy/express-cloudfoundry-actuator-middleware#4]
Node version: 15.8.0
express-cloudfoundry-actuator-middleware version: 1.4.0

I believe this warning shows on any version of Node > 12

**Comment by stfsy** [comment]
@zaneschepke will have a look and get back to you

**Comment by stfsy** [comment]
@zaneschepke should be fixed with https://github.com/stfsy/express-cloudfoundry-actuator-middleware/releases/v1.6.0. Relevant commit is https://github.com/stfsy/node-cloudfoundry-actuator/commit/47ad8a3367dedc301e0bf291be0558c7885ecb56

**Comment by zaneschepke** [comment]
After the update to 1.6 I am now getting the following error:

node-cloudfoundry-actuator/lib/security/request-response-sanitizer.js:17
        return this._sanitizedHeaders(req.getHeaders())
                                          ^

TypeError: req.getHeaders is not a function

**Comment by stfsy** [comment]
Oh. I'm sorry, that's the result of all this mocking... Let me setup some real tests tomorrow. I will release a working version afterwards.

**Comment by zaneschepke** [comment]
No worries, yeah I replaced it with just req.headers and that seemed to fix the issue. Thanks for looking into it!

**Comment by stfsy** [comment]
@zaneschepke I released an updated version of `node-cloudfoundry-actuator`. the newest release of `express-cloudfoundry-actuator-middleware` is [v1.7.0](https://github.com/stfsy/express-cloudfoundry-actuator-middleware/releases/tag/v1.7.0)

I tried on my machine with security disabled and it worked. Should work as expected on your machine(s) too 🙂
